# Generated by Django 3.0.1 on 2021-12-30 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_investment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Trading',
        ),
    ]
