# Generated by Django 3.0.1 on 2022-01-26 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20211230_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment',
            new_name='Blockchain',
        ),
    ]
