# Generated by Django 3.0.1 on 2022-01-30 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20220126_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Investment',
        ),
    ]
