# Generated by Django 3.0.1 on 2022-02-24 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20220203_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trading',
            new_name='Investing',
        ),
        migrations.RenameModel(
            old_name='DeFi',
            new_name='Theme',
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
    ]
