# Generated by Django 3.0.1 on 2022-02-26 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20220224_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Research',
        ),
    ]
