# Generated by Django 3.0.1 on 2022-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220226_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('price', models.TextField(max_length=100)),
                ('market_cap', models.TextField(max_length=100)),
                ('number_of_tokens', models.TextField(max_length=100)),
            ],
        ),
    ]
