# Generated by Django 3.0.1 on 2022-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220305_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_details', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='some-string')),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentSize',
        ),
        migrations.AddField(
            model_name='research',
            name='alt_text',
            field=models.TextField(default='some-string'),
        ),
        migrations.AddField(
            model_name='research',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
    ]
